### ISSUE TITLE
Add ability to setup a zone for CNAME hosting

### ISSUE THREAD

**Issue by RayeN** [yola/pycloudflare#27]
It can be done via `zone_set` API (https://www.cloudflare.com/docs/host-api/#s3.2.2)

Additional notes from Stefano: `We should play with zone_set to find out exactly what the requirements for the domain are. It looks like it may have the same "one level below TLD" restriction as CloudFlare's normal zones.`

**Comment by ekoval** [comment]
It might be a stupid question, but why do we need DNS to provide SSL hosting?
@stefanor , can you please explain?

**Comment by stefanor** [comment]
That's quite a fundamental question. DNS is how users connect to the web site. The domain owner has to publish DNS entries pointing to a server that can serve up the web site.

Currently, our WL users have A records pointing at the IP address of one of our hosting load balancers.

To provide SSL hosting, we are using CloudFlare to terminate the client's SSL connection, and proxy back to us. This is configured on CloudFlare's side, by creating a zone.

Because we don't have control of the user's domain, we can't delegate DNS to CloudFlare, as we would usually do, for one of our users. So, instead, we create a different type of CloudFlare zone (with the CNAME flag set). Then we ask the customer to publish a CNAME record, pointing to www.example.net.cdn.cloudflare.net. This way, CloudFlare can get and proxy the request to us, as usual.

**Comment by ekoval** [comment]
@stefanor 
Thanks for explanation. I still have a question - why. Why do we need this tricky scheme instead of just serving HTTPs and using DNS as DNS (name->ip converter)? 

So, how I imagine such things work:
1. User's browser resolves site name into IP using DNS subsystem.
2. Once the hostname is resolved, browser opens HTTP(s) connection (port 80(443)) to this IP.
3. Browser and server exchange data following HTTP(s) protocol.

I now understand how we're going to use CloudFlare - we're not going to serve HTTPs, we're going to support HTTP only. The thing I don't understand is why we did make this decision. Can you explain please?

**Comment by RayeN** [comment]
+1 to @ekoval's question.  I would like to know more about our current setup.
